-- Schema for the ExchangeRate entity
-- (com.exchange.exchangeratesystem.rate.ExchangeRate). Column types/
-- constraints mirror that entity's annotations exactly:
-- id BIGINT identity PK; currency_code VARCHAR(3) NOT NULL; rate_to_usd
-- DECIMAL(19,10) NOT NULL with a positivity check (@Check); rate_date DATE
-- NOT NULL; created_at/updated_at TIMESTAMP NOT NULL (set by the entity's
-- @PrePersist/@PreUpdate callbacks, not a DB default); a unique constraint
-- on (currency_code, rate_date), which ExchangeRateRepository#upsert's
-- ON CONFLICT target depends on.
CREATE TABLE exchange_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(3) NOT NULL,
    rate_to_usd DECIMAL(19,10) NOT NULL,
    rate_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_exchange_rate_currency_code_rate_date UNIQUE (currency_code, rate_date),
    CONSTRAINT ck_exchange_rate_rate_to_usd_positive CHECK (rate_to_usd > 0)
);
